apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: {{ .Release.Name }}-frontend-svc
  namespace: kanban
spec:
  ports:
  - name: frontend-port
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-service
  name: {{ .Release.Name }}-backend-svc
  namespace: kanban
spec:
  ports:
  - name: backend-port
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-frontend-svc
  labels:
    app: frontend-application
  namespace: kanban
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: frontend-port

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-backend-svc
  labels:
    app: backend-application
  namespace: kanban
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend-port

---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  image: quay.io/prometheus/prometheus
  serviceAccountName: prometheus
  replicas: 1
  serviceMonitorNamespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: kanban
  serviceMonitorSelector: {}
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false