apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend-service
  name: {{ .Release.Name }}-frontend-svc
  namespace: kanban
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 80
  selector:
    app: frontend
  type: ClusterIP
status:
  loadBalancer: {}

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-service
  name: {{ .Release.Name }}-frontend-svc
  namespace: kanban
spec:
  ports:
  - name: http
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: backend
  type: ClusterIP
status:
  loadBalancer: {}

