apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanban-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Okeybukks/hostspace-internship-capstone-project.git
    targetRevision: HEAD
    path: application_helm_chart
  destination:
    server: https://kubernetes.default.svc
    namespace: kanban
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kanban-application-database
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Okeybukks/hostspace-internship-capstone-project.git
    targetRevision: HEAD
    path: database
  destination:
    server: https://kubernetes.default.svc
    namespace: kanban
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-applications
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Okeybukks/hostspace-internship-capstone-project.git
    targetRevision: HEAD
    path: monitoring
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true