version: '3.8'
services:

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
    - grafana:/var/lib/grafana
    ports:
    - 3000:3000
    networks:
      - grafana
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml:ro
    ports:
      - 9090:9090
    networks:
      - grafana

  k6:
    image: loadimpact/k6:latest
    container_name: k6
    ports:
      - "6565:6565"
    networks:
      - grafana
    volumes:
      - ./:/test
    working_dir: "/test"
    entrypoint: [ "k6", "run",  "test/test.js", "--address", "0.0.0.0:6565" ]

  k6_exporter:
    image: savvagenchevskiy/k6-exporter:latest
    container_name: k6_exporter
    networks:
      - grafana
    ports:
      - 9091:9091
    environment:
      - METRICS_PORT=9091
      - COLLECT_INTERVAL=10
      - K6_SERVER=http://k6:6565
    depends_on:
      - k6

networks:
  grafana:

volumes:
  grafana:
  prometheus-data: