{
 "title": "HostSpace k6 Prometheus",
 "description": "Visualize k6 OSS results stored in Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile_stat", "label": "Trend Metrics Query", "query": { "query": "metrics(k6_http_req_duration_)" } },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "VUs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "k6_exporter_vus{instance=\"k6_exporter:9091\", job=\"k6_exporter\", running=\"true\", sample=\"vus\", server=\"http://k6:6565\", stopped=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max VUs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\nk6_exporter_vus{instance=\"k6_exporter:9091\", job=\"k6_exporter\", running=\"true\", sample=\"vus-max\", server=\"http://k6:6565\", stopped=\"false\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "avg(k6_exporter_vus{testid=~\"$testid\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "(label_replace(avg(k6_exporter_http_req_duration{testid=~\"$testid\"}), \"value\", \"$1s\", \"value\", \"(.*)\") / 60) * 10",
     "legendFormat": "http_req_duration_$quantile_stat"
    },
    {
     "expr": "k6_exporter_http_reqs{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"rate\", server=\"http://k6:6565\", type=\"counter\"}",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "k6_exporter_http_reqs{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"count\", server=\"http://k6:6565\", type=\"counter\"}",
     "legendFormat": "total_http_reqs"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "HTTP requests",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_exporter_http_reqs{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"count\", server=\"http://k6:6565\", type=\"counter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP request failures",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "round(k6_exporter_http_req_failed{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"rate\", server=\"http://k6:6565\", type=\"rate\"}, 0.1) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "k6_exporter_http_reqs{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"rate\", server=\"http://k6:6565\", type=\"counter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average HTTP Request Duration",
   "type": "stat",
   "description": "Select a different Stat to change the query",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "(k6_exporter_http_req_duration{sample=\"avg\",server=\"http://k6:6565\",type=\"trend\"})",
     "legendFormat": "Average HTTP Request Duration"
    }
   ]
  },
  {
   "title": "Transfer Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "k6_exporter_data_sent{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"count\", server=\"http://k6:6565\", type=\"counter\"} / 1000",
     "legendFormat": "data_sent"
    },
    {
     "expr": "k6_exporter_data_received{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"count\", server=\"http://k6:6565\", type=\"counter\"} /1000000",
     "legendFormat": "data_received"
    }
   ]
  },
  {
   "title": "Iterations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_exporter_iterations{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"count\", server=\"http://k6:6565\", type=\"counter\"}",
     "legendFormat": "iteration_count"
    },
    {
     "expr": "k6_exporter_iterations{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"rate\", server=\"http://k6:6565\", type=\"counter\"}",
     "legendFormat": "iteration_rate"
    }
   ]
  },
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "HTTP Latency Timings",
   "type": "timeseries",
   "description": "Select a different Stat to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "k6_exporter_http_req_blocked{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"avg\", server=\"http://k6:6565\", type=\"trend\"}",
     "legendFormat": "http_req_blocked_$quantile_stat"
    },
    {
     "expr": "k6_exporter_http_req_tls_handshaking{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"avg\", server=\"http://k6:6565\", type=\"trend\"}",
     "legendFormat": "http_req_tls_handshaking_$quantile_stat"
    },
    {
     "expr": "k6_exporter_http_req_sending{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"avg\", server=\"http://k6:6565\", type=\"trend\"} * 1000",
     "legendFormat": "http_req_sending_$quantile_stat"
    },
    {
     "expr": "k6_exporter_http_req_waiting{instance=\"k6_exporter:9091\", job=\"k6_exporter\", server=\"http://k6:6565\", type=\"trend\", value=\"avg\"}",
     "legendFormat": "http_req_waiting_$quantile_stat"
    },
    {
     "expr": "k6_exporter_http_req_duration{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"avg\", server=\"http://k6:6565\", type=\"trend\"}",
     "legendFormat": "http_req_duration_$quantile_stat"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "k6_exporter_http_reqs{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"rate\", server=\"http://k6:6565\", type=\"counter\"}",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "k6_exporter_http_reqs{instance=\"k6_exporter:9091\", job=\"k6_exporter\", sample=\"count\", server=\"http://k6:6565\", type=\"counter\"}\n\n",
     "legendFormat": "http_reqs_total"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_success"
    }
   ]
  },
  {
   "title": "Checks Success Rate (aggregate individual checks)",
   "type": "timeseries",
   "description": "Filter by check name to query a particular check",
   "gridPos": { "h": 7, "w": 13, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "k6_exporter_checks_passes{instance=\"k6_exporter:9091\", job=\"k6_exporter\", name=\"status was 200\", path=\"::status was 200\", server=\"http://k6:6565\"}",
     "legendFormat": "k6_checks_rate"
    },
    {
     "expr": "k6_exporter_checks_fails{instance=\"k6_exporter:9091\", job=\"k6_exporter\", name=\"status was 200\", path=\"::status was 200\", server=\"http://k6:6565\"}",
     "legendFormat": "checks_failure"
    }
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "description": "min/max/p95/p99 depends on the available Quantile Stats",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 40 },
   "targets": [
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_min{testid=~\"$testid\"})",
     "legendFormat": "min"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_max{testid=~\"$testid\"})",
     "legendFormat": "max"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_p95{testid=~\"$testid\"})",
     "legendFormat": "p95"
    },
    {
     "expr": "avg by(name, method, status) (k6_http_req_duration_p99{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Checks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 48 },
   "options": {
    "content": "### Visualize other k6 results  \n\nAt the top of the dashboard, click `Add` and select `Visualization` from the dropdown menu. Choose the visualization type and input the PromQL queries for the `k6_` metric(s).\n\nAlternatively, click on the `Explore` icon on the menu bar and input the queries for the `k6_` metric(s). From `Explore`, you can add new Panels to this dashboard. \n\nNote that all <a href=\"https://k6.io/docs/using-k6/metrics/\" target=\"_blank\">k6 metrics</a> are prefixed with the `k6_` namespace when sent to Prometheus."
   }
  }
 ]
}