apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadvisor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
  - repoURL: oci://registry-1.docker.io/kubestar
    chart: cadvisor
    targetRevision: 0.1.15
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true