apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/Okeybukks/hostspace-internship-capstone-project.git
      targetRevision: HEAD
      ref: main
      path: monitoring
    - repoURL: https://prometheus-community.github.io/helm-charts/
      chart: prometheus
      targetRevision: 25.18.0
      helm:
        values: |
          extraScrapeConfigs:
            - job_name: 'mongodb'
              static_configs:
                - targets: ['mongodb-exporter-prometheus-mongodb-exporter:9216'] 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true