apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: kanban
  labels:
    name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb-port
  clusterIP: None
  selector:
    app: mongodb