apiVersion: v1
kind: Service
metadata:
  name: mongo
  # annotations:
  #   prometheus.io/scrape: 'true'
  #   prometheus.io/port:   '9090'
  namespace: kanban
  labels:
    name: mongodb
spec:
  ports:
    - port: 27017
      targetPort: 27017
  clusterIP: None
  selector:
    app: mongodb