apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-monitor
  namespace: monitoring
  labels:
    release: prometheus-stack
    app: prometheus
spec:
  selector:
    matchLabels:
      name: prometheus-mongodb-exporter
  endpoints:
  - port: metrics
