name: Build Docker Image

run-name: ${{ github.actor }}

on: [push]

jobs:
  check-bats-version:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        name: Checkout repository

      - run: cd ./application
      - run: ls

        

      