name: Build Docker Image

run-name: ${{ github.actor }}

on: [push]

jobs:
  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Terraform Init
      id: init
      working-directory: ./terraform
      run: terraform init

    - name: Terraform Apply
      id: apply
      run: terraform apply --auto-approve
      working-directory: ./terraform
    

        

      