name: Build Docker Image

run-name: ${{ github.actor }}

on: [push]

jobs:
  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: hashicorp/setup-terraform@v3

    - name: Setup AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    # - name: Terraform Init
    #   id: init
    #   working-directory: ./terraform
    #   run: terraform init

    # - name: Terraform Apply
    #   id: apply
    #   run: terraform apply --auto-approve
    #   working-directory: ./terraform

    - name: Build and Push Container to ECR
      uses: GlueOps/github-actions-build-push-containers@v0.3.6
      with:
        registry: "${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/hostspace"
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: us-east-1

    - name: Build Image
      working-directory: ./application/backend
      run: docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/hostspace/backend:$GITHUB_RUN_NUMBER .

    - name: Get Image
      run: docker images

        

      