name: Build Docker Image

run-name: ${{ github.actor }}

on: [push]

jobs:
  build-docker-images:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4
        name: Checkout repository

      - run: ls ./application

        

      