name: Build Docker Image 

run-name: ${{ github.actor }}

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - 'application_source_code/backend/**'
    - 'application_source_code/frontend/**'
jobs:
  build-docker-images:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
  
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker backend application image
      working-directory: application_source_code/backend
      run: docker build -t achebeh/kanban-backend:latest .

    - name: Build Docker frontend application image
      working-directory: application_source_code/frontend
      run: docker build -t achebeh/kanban-frontend:latest .

    - name: Push Docker image to Docker Hub
      run: docker push achebeh/kanban-frontend:latest      

      
