name: Create Kubernetes Cluster

run-name: Create Kubernetes Cluster

on:
  push:
    branches:
    - main
    # paths:
    # - 'kubernetes_cluster/**'

jobs:
    create-kubernetes-cluster:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: Checkout repository

            - name: Install awscli and eksctl
              working-directory: ./kubernetes_cluster
              run: bash awscli_eksctl_installation_script.sh

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: List s3 buckets
              run: aws s3 ls
            
            - name: Test Helm
              run: helm version

            - name: Test Kubectl
              run: kubectl version
                
