name: Create Kubernetes Cluster

run-name: Create Kubernetes Cluster

on:
  workflow_dispatch:
  push:
    branches:
    - branch/final-submission
    paths:
    - 'kubernetes_cluster/**'

jobs:
    create-kubernetes-cluster:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
              name: Checkout repository

            - name: Install awscli, eksctl, helm and kubectl
              working-directory: ./kubernetes_cluster
              run: bash awscli_eksctl_installation_script.sh

            - name: Setup AWS Credentials
              uses: aws-actions/configure-aws-credentials@v2
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: us-east-1

            - name: Create Kubernetes Cluster with eksctl
              working-directory: ./kubernetes_cluster
              run: bash eks_script.sh

            - name: Update kubectl to use created EKS cluster
              run: aws eks update-kubeconfig --region us-east-1 --name hostspace-cluster
            
            - name: Create Node Provisioner for Karpenter
              working-directory: ./kubernetes_cluster
              run: bash node_provisioner.sh

            - name: Install Argocd
              run: |
                kubectl create namespace argocd
                kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
                
            - name: Install Sealed Secret Controller to Cluster
              run: |
                helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
                helm install sealed-secrets -n kube-system --set-string fullnameOverride=sealed-secrets-controller sealed-secrets/sealed-secrets

            - name: Install Nginx Ingress Controller
              working-directory: ./ingress_controller
              run: |
                helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
                helm repo update
                kubectl create ns ingress
                helm install application-ingress ingress-nginx/ingress-nginx --namespace ingress --values values.yaml
            
            - name: Install Cert Manager
              working-directory: ./ingress_controller
              run: |
                helm repo add jetstack https://charts.jetstack.io --force-update
                helm install cert-manager jetstack/cert-manager --namespace cert-manager --create-namespace --set installCRDs=true

            - name: Create Staging and Production Cluster Issuers for Ingress Controller
              working-directory: ./ingress_controller
              run: |
                kubectl create -f lets-encrypt-staging.yaml 
                kubectl create -f lets-encrypt-production.yaml 

            - name: Setting Up EBS storageclass add-ons for the cluster
              working-directory: ./storageclass_configurations
              run: bash storageclass_setup.sh