name: Create Kubernetes Cluster

run-name: ${{ github.actor }}

on:
  push:
    branches:
    - main
    # paths:
    # - 'kubernetes_cluster/**'

jobs:
    create-kubernetes-cluster:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Upload files
              uses: hannut91/aws-cli@v1.18.43
              with:
                args: s3 ls
              env:
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_DEFAULT_REGION: ap-northeast-2