name: 'Helm Templating'

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/test'

jobs:
  templating:
    env:
      HELM_VERSION: 3.14.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm Chart repository
        uses: actions/checkout@v3
        with:
          repository: Okeybukks/hostspacecloud
          ref: main
          path: helm-chart
          token: ${{ secrets.TOKEN }}

      - name: Checkout Helm Chart repository2
        uses: actions/checkout@v3
        path: helm

      # - name: Install Helm
      #   run: |
      #     sudo curl -L -o /usr/bin/helm https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
      #     sudo chmod +x /usr/bin/helm
      
      - name: check pulled repo
        run: ls helm-chart