name: 'Helm Templating'

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/test'

jobs:
  templating:
    env:
      HELM_VERSION: 3.14.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm Chart repository
        uses: actions/checkout@v3
        with:
          repository: Okeybukks/hostspacecloud
          ref: main
          path: helm-chart
          token: ${{ secrets.TOKEN }}

      - name: Checkout Helm Chart repository2
        uses: actions/checkout@v3
        with:
          repository: Okeybukks/hostspace-internship-capstone-project
          ref: feature/test
          path: helm-chart2
        
      - name: Install Helm
        run: |
          sudo curl -L -o /usr/bin/helm https://get.helm.sh/helm-v${HELM_VERSION}-linux-amd64.tar.gz
          sudo chmod +x /usr/bin/helm
      
      - name: check pulled repo
        run: helm template helm-chart2/application_helm_chart --values helm-chart/values.yaml > ${{ github.workspace }}/test.yaml

      - name: Set up Kubeconform
        uses: bmuschko/setup-kubeconform@v1
    
      - name: Validate manifests
        run: |
          kubeconform -schema-location default -schema-location 'https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/{{.Group}}/{{.ResourceKind}}_{{.ResourceAPIVersion}}.json' \
          -summary -verbose ${{ github.workspace }}/test.yaml


