name: 'Helm Templating'

on:
  workflow_dispatch:
  push:
    branches:
      - 'feature/test'

jobs:
  templating:
    env:
      HELM_VERSION: 3.14.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Helm Chart repository
        uses: actions/checkout@v3
        with:
          repository: Okeybukks/hostspacecloud
          ref: feature/test
          # path: .
      
      - name: check pulled repo
        run: ls