# Default values for kanban-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

kanbanBackendIP: https://api.achebeh.site

images:
  frontend:
      repository: achebeh/kanban-frontend
      pullPolicy: IfNotPresent
      tag: "latest"
  backend:
      repository: achebeh/kanban-backend
      pullPolicy: IfNotPresent
      tag: "latest"
